// captionGenerator.mjs

const captions = [
  "🧠 Can you solve this math challenge? Comment your answer below! 👇",
  "🔥 Only smart students can solve this one. What's your answer?",
  "🎯 Test your IQ with today's math puzzle!",
  "🚀 Quick math challenge! Can you solve it without a calculator?",
  "😎 Most people get this wrong. Will you?",
  "⚡ Math Genius Challenge! Drop your answer below.",
  "🏆 Can you beat this puzzle in under 10 seconds?",
  "🤔 Think carefully before answering...",
  "💡 Sharpen your brain with today's challenge!",
  "🧮 Let's see who is best at math today!",
  "🎓 Student Challenge of the Day!",
  "🔥 Comment A, B, C or D and let's see who's right!",
  "🚨 New IQ Test Just Dropped!",
  "🧠 Brain Workout Time! Solve this if you can.",
  "😲 95% of students fail this challenge!",
  "🏅 Only top students can solve this quickly.",
  "🎯 Can you get the correct answer on your first try?",
  "⚡ No calculator allowed! What's your answer?",
  "🚀 Math Battle: You vs This Question!",
  "💯 Are you smarter than your friends?",
  "👑 Only legends can solve this challenge.",
  "🧠 Your brain deserves a workout today.",
  "🔥 Can you solve it before reading the comments?",
  "⚡ Warning: This question is trickier than it looks.",
  "🎯 Challenge accepted? Let's see your answer.",
  "🚨 Don't scroll without solving this!",
  "🤯 This puzzle is breaking the internet today.",
  "💪 Train your brain one question at a time.",
  "🧠 Math lovers, this one is for you.",
  "😏 Easy or impossible? You decide.",
  "🏆 Prove your math skills in the comments.",
  "⚡ Let's separate geniuses from the crowd.",
  "🚀 Can you solve this in under 5 seconds?",
  "🎓 School students, can you crack this one?",
  "🧮 Brain power check! What's the answer?",
  "🔥 Everyone is arguing about this answer.",
  "🤔 Which option is correct? A, B, C or D?",
  "😎 Challenge your friends with this puzzle.",
  "🎯 One question. Four options. One winner.",
  "🚀 Are you smarter than the average student?",
  "💡 Think before you answer.",
  "🧠 Today's challenge is not as easy as it seems.",
  "⚡ Can your IQ handle this question?",
  "🏅 Fast thinkers, let's see your answer.",
  "🤯 Only 1 in 10 people get this right.",
  "🔥 Math challenge of the day is here!",
  "🎓 Ready for today's brain test?",
  "🧠 Give your best guess before checking comments.",
  "🚀 Can you solve this before your friends?",
  "💯 Let's find the math champion today.",
  "⚡ Brain vs Puzzle. Who wins?",
  "🏆 The answer may surprise you.",
  "🤔 Don't overthink it... or should you?",
  "🔥 How fast can you solve this?",
  "🎯 The clock is ticking. What's your answer?",
  "🧠 Genius test starts now.",
  "🚨 Think you know math? Prove it.",
  "😲 Almost everyone gets this wrong.",
  "🏅 Can you join the top 1%?",
  "⚡ Are you ready for a real challenge?",
  "🎓 Show your calculation skills.",
  "🧠 Brain teaser incoming!",
  "🔥 This question looks easy but isn't.",
  "🚀 Let's see who solves it first.",
  "💡 Focus and solve carefully.",
  "🤯 The answer isn't what most people think.",
  "🎯 Your turn to shine.",
  "🏆 Can you earn math champion status today?",
  "🧠 Solve it and tag a friend.",
  "⚡ Don't let this puzzle defeat you.",
  "🔥 Ready for another IQ challenge?",
  "🎓 Every smart student should try this.",
  "🚀 One puzzle. Unlimited bragging rights.",
  "🤔 Which option are you choosing?",
  "🧠 Test your logic, not your luck.",
  "💯 How confident are you in your answer?",
  "🏅 Only quick thinkers will get this right.",
  "⚡ This puzzle has everyone confused.",
  "🔥 Can you spot the correct answer instantly?",
  "🎯 A small question with a big challenge.",
  "🧠 Time to wake up your brain.",
  "🚨 Stop scrolling and solve this.",
  "🤯 This one is harder than yesterday's.",
  "🏆 Are you the smartest in the comments?",
  "⚡ Math warriors, assemble!",
  "🎓 Challenge your classmates with this.",
  "🔥 Can you solve this without pen and paper?",
  "🧠 Let's see your mental math skills.",
  "💡 One of these options is correct. Which one?",
  "🚀 The answer is waiting for you.",
  "🤔 Think twice before commenting.",
  "🏅 Let's see who gets it right first.",
  "⚡ This challenge is for true problem solvers.",
  "🎯 Ready to test your brain?",
  "🔥 Can you beat today's challenge?",
  "🧠 Only the sharpest minds will solve this.",
  "🚀 Your daily dose of brain training.",
  "🏆 Comment your answer and challenge your friends."
];

const hashtags = [
  "#MathChallenge",
  "#MathPuzzle",
  "#BrainTeaser",
  "#IQTest",
  "#Students",
  "#Education",
  "#Math",
  "#Learning",
  "#Quiz",
  "#Challenge",
  "#School",
  "#BrainGame",
  "#Knowledge",
  "#Study",
  "#SmartStudents",

  "#MentalMath",
  "#MathProblems",
  "#MathQuestion",
  "#MathTricks",
  "#MathTeacher",
  "#Maths",
  "#MathLovers",
  "#MathFun",
  "#MathFacts",
  "#MathMagic",

  "#BrainChallenge",
  "#BrainTraining",
  "#BrainWorkout",
  "#BrainPower",
  "#BrainBoost",
  "#BrainExercise",
  "#BrainTest",
  "#BrainPuzzle",
  "#MindChallenge",
  "#MindGames",

  "#Puzzle",
  "#Puzzles",
  "#PuzzleChallenge",
  "#PuzzleTime",
  "#PuzzleGame",
  "#DailyPuzzle",
  "#DailyChallenge",
  "#DailyQuiz",
  "#DailyLearning",
  "#DailyBrainTeaser",

  "#QuizTime",
  "#QuizChallenge",
  "#QuizOfTheDay",
  "#Trivia",
  "#QuestionOfTheDay",
  "#GuessTheAnswer",
  "#CommentYourAnswer",
  "#ThinkFast",
  "#ThinkSmart",
  "#ThinkDifferent",

  "#Genius",
  "#GeniusMind",
  "#GeniusChallenge",
  "#Smart",
  "#SmartPeople",
  "#SmartKids",
  "#SmartLearning",
  "#SmartThinking",
  "#TopStudents",
  "#FutureGenius",

  "#StudentLife",
  "#SchoolLife",
  "#ExamPreparation",
  "#StudyTime",
  "#StudyGram",
  "#LearningIsFun",
  "#EducationMatters",
  "#LearnEveryday",
  "#LearnAndGrow",
  "#KnowledgeIsPower",

  "#CompetitiveExam",
  "#Aptitude",
  "#Reasoning",
  "#LogicalThinking",
  "#CriticalThinking",
  "#ProblemSolving",
  "#AnalyticalThinking",
  "#MentalAbility",
  "#QuickThinking",
  "#FastThinking",

  "#ViralQuiz",
  "#TrendingQuiz",
  "#ViralChallenge",
  "#TrendingNow",
  "#ExplorePage",
  "#ExploreMore",
  "#ReelsIndia",
  "#IndianStudents",
  "#StudentCommunity",
  "#EducationIndia",

  "#MathReels",
  "#QuizReels",
  "#BrainReels",
  "#EducationalContent",
  "#EducationalReels",
  "#LearningReels",
  "#KnowledgeReels",
  "#StudyMotivation",
  "#StudentMotivation",
  "#AcademicSuccess",

  "#CanYouSolveIt",
  "#OnlyForGeniuses",
  "#OnlySmartPeople",
  "#ChallengeAccepted",
  "#TestYourIQ",
  "#TestYourBrain",
  "#SolveThis",
  "#MathQuiz",
  "#IQChallenge",
  "#GeniusTest",

  "#Numbers",
  "#Arithmetic",
  "#Calculation",
  "#MentalCalculation",
  "#NumberPuzzle",
  "#Equation",
  "#SolveTheEquation",
  "#MathCompetition",
  "#MathPractice",
  "#MathSkills",

  "#FunLearning",
  "#LearnWithFun",
  "#EducationForAll",
  "#LearningCommunity",
  "#KnowledgeSharing",
  "#StudyChallenge",
  "#SchoolChallenge",
  "#ExamTips",
  "#LearningJourney",
  "#SuccessMindset"
];

function shuffle(array) {
  return [...array].sort(
    () => Math.random() - 0.5
  );
}

export function generateCaption() {
  const caption =
    captions[
      Math.floor(
        Math.random() *
          captions.length
      )
    ];

  const selectedTags =
    shuffle(hashtags)
      .slice(0, 4)
      .join(" ");

  return `${caption}

👇 Comment your answer below!

${selectedTags}`;
}